export default defineAppConfig({
  ui: {
    colors: {
      primary: 'bego',
      neutral: 'zinc',
    },
    icons: {
      arrowUp: 'i-mingcute-arrow-up-fill',
      arrowDown: 'i-mingcute-arrow-down-fill',
      caution: 'i-mingcute-warning-fill',
      copy: 'i-mingcute-copy-2-fill',
      copyCheck: 'i-mingcute-check-2-fill',
      dark: 'i-mingcute-moon-fill',
      error: 'i-mingcute-close-circle-fill',
      external: 'i-mingcute-external-link-fill',
      eye: 'i-mingcute-eye-2-fill',
      eyeOff: 'i-mingcute-eye-close-fill',
      file: 'i-mingcute-file-fill',
      folder: 'i-mingcute-folder-fill',
      folderOpen: 'i-mingcute-folder-open-fill',
      hash: 'i-mingcute-hashtag-fill',
      info: 'i-mingcute-information-fill',
      light: 'i-mingcute-sun-fill',
      menu: 'i-mingcute-menu-fill',
      panelClose: 'i-mingcute-layout-leftbar-close-fill',
      panelOpen: 'i-mingcute-layout-leftbar-open-fill',
      reload: 'i-mingcute-refresh-anticlockwise-1-fill',
      stop: 'i-mingcute-stop-fill',
      success: 'i-mingcute-check-circle-fill',
      system: 'i-mingcute-computer-fill',
      tip: 'i-mingcute-light-fill',
      warning: 'i-mingcute-alert-fill',
      arrowLeft: 'i-mingcute-arrow-left-fill',
      arrowRight: 'i-mingcute-arrow-right-fill',
      check: 'i-mingcute-check-fill',
      chevronDoubleLeft: 'i-mingcute-arrows-left-fill',
      chevronDoubleRight: 'i-mingcute-arrows-right-fill',
      chevronDown: 'i-mingcute-down-fill',
      chevronLeft: 'i-mingcute-left-fill',
      chevronRight: 'i-mingcute-right-fill',
      chevronUp: 'i-mingcute-up-fill',
      close: 'i-mingcute-close-fill',
      ellipsis: 'i-mingcute-more-1-fill',
      loading: 'i-mingcute-loading-fill',
      minus: 'i-mingcute-minimize-fill',
      plus: 'i-mingcute-add-fill',
      search: 'i-mingcute-search-3-fill',
    },
  },
})
